spring:
  application:
    name: shopping-store

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5433/hub_router
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5

logging:
  level:
    ru.yandex.practicum: DEBUG